"""Report Agent - Consolidates findings into comprehensive reports."""

from typing import Dict, Any
from shared.models import (
    AgentResult, AgentTask, Finding, ConfidenceLevel, Source, SourceType
)
from agents.base_agent import BaseAgent
from datetime import datetime


class ReportAgent(BaseAgent):
    """Generates comprehensive reports from all agent findings."""

    def __init__(self):
        super().__init__(
            name="report_agent",
            description="Report generation - consolidation and synthesis"
        )

    def analyze(self, task: AgentTask, context: Dict[str, Any]) -> AgentResult:
        """Generate comprehensive report."""
        topic = context.get("investigation_topic", "")
        self.logger.info(f"Generating report for: {topic}")

        previous_results = context.get("previous_results", {})

        # Build report
        report = self._build_report(topic, previous_results)

        # Create finding for the report
        findings = [Finding(
            title="Investigation Report Generated",
            description="Comprehensive analysis report",
            evidence=[
                f"Topic: {topic}",
                f"Agents analyzed: {len(previous_results)}",
                f"Timestamp: {datetime.utcnow().isoformat()}"
            ],
            confidence=ConfidenceLevel.HIGH,
            sources=[Source(
                type=SourceType.INTERNAL_ANALYSIS,
                title="Report Agent",
                reliability_score=0.9
            )]
        )]

        return AgentResult(
            agent_name=self.name,
            task_id=task.id,
            objective=task.objective,
            findings=findings,
            recommendations=report,
            metadata={"report": report}
        )

    def _build_report(self, topic: str, previous_results: Dict) -> str:
        """Build comprehensive markdown report."""
        report = f"""# 🐝 PROYECTO COLMENA - INVESTIGATION REPORT
## {topic}
**Generated:** {datetime.utcnow().isoformat()}

---

## EXECUTIVE SUMMARY

This is a comprehensive analysis of **{topic}** generated by PROYECTO COLMENA's multiagent system.

---

"""

        # Add agent results
        report += "## AGENT ANALYSIS RESULTS\n\n"

        for agent_name, result in previous_results.items():
            report += f"### {agent_name.upper()}"
            report += f"\n**Status:** {result.status}\n"
            report += f"**Duration:** {result.duration_seconds:.2f}s\n"
            report += f"**Confidence:** {result.overall_confidence().name}\n"
            report += f"**Findings:** {len(result.findings)}\n\n"

            if result.findings:
                for finding in result.findings:
                    report += f"#### {finding.title}\n"
                    report += f"{finding.description}\n\n"
                    if finding.evidence:
                        report += "**Evidence:**\n"
                        for ev in finding.evidence:
                            report += f"- {ev}\n"
                        report += "\n"

            if result.recommendations:
                report += f"**Recommendation:** {result.recommendations}\n\n"

            if result.risks:
                report += "**Identified Risks:**\n"
                for risk in result.risks:
                    report += f"- {risk}\n"
                report += "\n"

            report += "---\n\n"

        # Summary section
        report += """## KEY TAKEAWAYS

1. This analysis is based on multiple specialized agents
2. Each finding includes confidence levels and sources
3. Risks have been identified and should be carefully considered
4. This is for information and analysis purposes only
5. No financial advice is provided

---

## METHODOLOGY

This investigation was conducted using PROYECTO COLMENA's multiagent architecture:

- **Research Agent**: Gathers information from multiple sources
- **Financial Agent**: Analyzes fundamental metrics
- **Technical Agent**: Evaluates price patterns and indicators
- **Sentiment Agent**: Assesses market mood and news sentiment
- **Macro Agent**: Provides economic context
- **Risk Agent**: Identifies potential risks
- **Devil's Advocate**: Challenges conclusions and assumptions
- **Report Agent**: Synthesizes findings

---

## NEXT STEPS

1. Review all findings carefully
2. Consider alternative scenarios
3. Perform additional due diligence if needed
4. Consult with financial advisors
5. Monitor for new information

---

**DISCLAIMER:** This report is generated by AI agents for informational purposes only. It is not financial advice. Always conduct your own due diligence and consult with professionals before making any decisions.

*Generated by PROYECTO COLMENA*
"""

        return report
